#!/bin/bash

/usr/local/bin/mise trust /workspaces/blog-notes/mise.toml && /usr/local/bin/mise install

sudo apt update && sudo apt install -y build-essential

sudo apt install tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
